# configure zsh shell
- name: ZSH - Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
- name: ZSH - Copy .zshrc template config
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
- name: ZSH - Set eastwood theme in .zshrc
  ansible.builtin.replace:
    path: ~/.zshrc
    regexp: 'ZSH_THEME=".+"'
    replace: 'ZSH_THEME="eastwood"'
- name: ZSH - Install zsh syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
- name: ZSH - Install zsh zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
- name: ZSH - Set zsh plugins in .zshrc
  ansible.builtin.replace:
    path: ~/.zshrc
    regexp: 'plugins=\(.+\)'
    replace: "plugins=(git zsh-syntax-highlighting zsh-autosuggestions)"