- hosts: services
  pre_tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /data/grafana/data
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
  tasks:
    - name: Allow all access to TCP port 3001 (Grafana)
      community.general.ufw:
        rule: allow
        port: '3001'
        proto: tcp
    - name: Start grafana in a docker container
      community.docker.docker_container:
        name: grafana
        hostname: grafana
        image: grafana/grafana-oss:latest
        pull: true
        restart: true
        restart_policy: unless-stopped
        user: root
        ports:
          - "3010:3000"
        volumes:
          - /data/grafana/data:/var/lib/grafana
        links:
          - victoria-metrics